# Generated by Django 6.1.1 on 2026-10-01 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=50, unique=True)),
                ('user_id', models.CharField(max_length=50)),
                ('recipient_id', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('recipient_new', models.BooleanField(default=False)),
                ('device_changed', models.BooleanField(default=False)),
                ('location_changed', models.BooleanField(default=False)),
                ('transactions_last_1h', models.IntegerField(default=0)),
                ('average_transaction_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('account_age_days', models.IntegerField(default=0)),
                ('risk_score', models.FloatField(default=0)),
                ('risk_level', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='LOW', max_length=10)),
                ('is_suspicious', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
