# Generated by Django 6.1.1 on 2026-10-07 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='analyst_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('REVIEWED', 'Reviewed'), ('ESCALATED', 'Escalated'), ('CLEARED', 'Cleared')], db_index=True, default='PENDING', max_length=10),
        ),
        migrations.AddField(
            model_name='transaction',
            name='anomaly_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='transaction',
            name='behavioral_anomaly',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transaction',
            name='behavioral_features',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='transaction',
            name='fraud_probability',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='transaction',
            name='risk_factors',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='transaction',
            name='user_verified',
            field=models.BooleanField(default=False),
        ),
    ]
