# Generated by Django 6.1.1 on 2026-10-07 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_transaction_analyst_status_transaction_anomaly_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='recommendation',
            field=models.JSONField(default=dict),
        ),
    ]
