# Generated by Django 6.1.1 on 2026-10-07 04:15

from django.db import migrations, models


def seed_demo_recipients(apps, schema_editor):
    Recipient = apps.get_model("transactions", "Recipient")
    Transaction = apps.get_model("transactions", "Transaction")
    database = schema_editor.connection.alias
    recipient_ids = set(
        Transaction.objects.using(database)
        .values_list("recipient_id", flat=True)
        .distinct()
    )
    recipient_ids.update(
        {
            "R0101",
            "R0102",
            "R0205",
            "R0310",
            "01711223344",
            "01899887766",
            "R9901",
            "R9942",
            "01300998877",
            "01999112233",
        }
    )
    Recipient.objects.using(database).bulk_create(
        [Recipient(recipient_id=recipient_id) for recipient_id in recipient_ids],
        ignore_conflicts=True,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_transaction_recommendation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('recipient_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
        ),
        migrations.RunPython(seed_demo_recipients, migrations.RunPython.noop),
    ]
