# Generated by Django 6.1.1 on 2026-10-07 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_recipient'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user_id', 'created_at'], name='txn_user_created_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user_id', 'recipient_id', 'created_at'], name='txn_user_rec_created_idx'),
        ),
    ]
